// src/layouts/Layout.jsx
import { useEffect, useMemo, useState } from 'react'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { Menu, Button, Avatar, Dropdown, Typography, Tooltip, Badge } from 'antd'
import {
  HomeOutlined, RobotOutlined, AudioOutlined, AimOutlined,
  ToolOutlined, ScanOutlined, DesktopOutlined, FormOutlined,
  BgColorsOutlined, BarChartOutlined, DashboardOutlined, AppstoreOutlined,
  CodeOutlined, BellOutlined, TableOutlined, LockOutlined, CodepenOutlined,
  ExperimentOutlined, InfoCircleOutlined, SwapOutlined,
  MenuFoldOutlined, MenuUnfoldOutlined,
  EyeInvisibleOutlined, EyeOutlined,
  LogoutOutlined, ThunderboltOutlined,
  DownOutlined,
  ApiOutlined, InteractionOutlined, ShareAltOutlined,
  TeamOutlined, PartitionOutlined, AimOutlined as AimO2,
  FundProjectionScreenOutlined,
  DeploymentUnitOutlined,
  MessageOutlined,
} from '@ant-design/icons'
import { useAuth } from '../contexts/useAuth.js'
import { useStyleMode } from '../contexts/StyleModeContext.jsx'
import Assistants from '../components/Assistants/index.jsx'
import VueMenu from '../components/VueMenu/index.jsx'
import './Layout.scss'

const { Text } = Typography

/* —— 导航配置：icon 全部用 antd 图标组件 —— */
const navItems = [
  { key: '/', icon: <HomeOutlined />, label: '首页' },
  {
    key: 'group-ai', icon: <RobotOutlined />, label: 'AI 助手',
    children: [
      { key: '/chatbot', icon: <MessageOutlined />, label: '对话助手 ChatBot' },
      { key: '/share', icon: <ShareAltOutlined />, label: '对话分享 QASharing' },
      { key: '/voice', icon: <AudioOutlined />, label: '语音助手' },
      { key: '/agent', icon: <AimOutlined />, label: 'AI Agent 控制台' },
    ],
  },
  {
    key: 'group-toolbox', icon: <ToolOutlined />, label: '工具箱',
    children: [
      { key: '/scan', icon: <ScanOutlined />, label: '扫码' },
      { key: '/kit', icon: <ThunderboltOutlined />, label: '组件工具箱 Kit' },
      { key: '/studio', icon: <CodepenOutlined />, label: '组件工坊 Studio' },
  { key: '/templates', icon: <AppstoreOutlined />, label: '开源模板库' },
  { key: '/utils', icon: <ToolOutlined />, label: '小功能集 Utils' },
      { key: '/embed', icon: <DesktopOutlined />, label: '嵌套预览' },
      { key: '/form-builder', icon: <FormOutlined />, label: '配置表单' },
      { key: '/theme', icon: <BgColorsOutlined />, label: '主题切换' },
      { key: '/charts', icon: <BarChartOutlined />, label: 'SVG 图表' },
      { key: '/echarts', icon: <DashboardOutlined />, label: 'ECharts 仪表盘' },
      { key: '/command-palette', icon: <CodeOutlined />, label: '命令面板' },
      { key: '/notify', icon: <BellOutlined />, label: '通知中心' },
      { key: '/data-table', icon: <TableOutlined />, label: '高级表格' },
      { key: '/login', icon: <LockOutlined />, label: '星空登录' },
      { key: '/assistant-demo', icon: <ThunderboltOutlined />, label: '快捷助手' },
    ],
  },
  {
    key: 'group-compare', icon: <FundProjectionScreenOutlined />, label: '组件对比中心',
    children: [
      { key: '/antd', icon: <AppstoreOutlined />, label: 'Ant Design 组件库' },
      { key: '/vue-components', icon: <CodeOutlined />, label: 'Vue 组件库 (.vue)' },
      { key: '/angular-components', icon: <DeploymentUnitOutlined />, label: 'Angular 组件库 (.ts)' },
      { key: '/style-showcase', icon: <SwapOutlined />, label: '样式总对比' },
      {
        key: '__sep-compare__',
        disabled: true,
        className: 'menu-sep-title',
        label: (
          <span className="sep-title">
            <span className="sep-title__line" />
            <span className="sep-title__text">专题对比案例</span>
            <span className="sep-title__line" />
          </span>
        ),
      },
      { key: '/compare-parent-child', icon: <ApiOutlined />, label: '父子组件传值' },
      { key: '/compare-two-way', icon: <InteractionOutlined />, label: '双向绑定' },
      { key: '/compare-provide', icon: <ShareAltOutlined />, label: '跨层传值 (Provide/Inject)' },
      { key: '/compare-state', icon: <TeamOutlined />, label: '全局状态共享' },
      { key: '/compare-slot', icon: <PartitionOutlined />, label: '插槽 / Children 分发' },
      { key: '/compare-ref', icon: <AimO2 />, label: 'Ref / DOM 操作' },
    ],
  },
  { key: '/dashboard', icon: <DashboardOutlined />, label: '控制台' },
  { key: '/test-center', icon: <ExperimentOutlined />, label: '测试中心' },
  { key: '/about', icon: <InfoCircleOutlined />, label: '关于' },
]

/* 默认展开哪个分组 */
const DEFAULT_OPEN_KEYS = ['group-toolbox', 'group-compare']

const LS_KEY = 'app.layout.v1'
const DEFAULT = { sidebarMode: 'expanded', headerVisible: true, openKeys: DEFAULT_OPEN_KEYS }

function readLayout() {
  try {
    const raw = localStorage.getItem(LS_KEY)
    if (!raw) return DEFAULT
    const parsed = JSON.parse(raw)
    return {
      ...DEFAULT,
      ...parsed,
      openKeys: parsed.openKeys?.length ? parsed.openKeys : DEFAULT_OPEN_KEYS,
    }
  } catch { return DEFAULT }
}
function writeLayout(v) {
  try { localStorage.setItem(LS_KEY, JSON.stringify(v)) } catch { /* ignore */ }
}

/**
 * 布局结构（严格一个滚动容器：.app-main-scroll）
 *
 *  .app-shell                       flex-col / h-screen / overflow-hidden  ← 全局不滚动
 *  ├─ header  .app-header           flex / height: var(--lh, 64px) 可隐藏（lh=0）
 *  ├─ section .app-body             flex / flex-1 / min-h-0 / overflow-hidden
 *  │    ├─ aside .app-sidebar       width: var(--sw) / flex-shrink-0 三态
 *  │    └─ div   .app-main-wrap     flex-1 / min-w-0 / display:flex / flex-col
 *  │          └─ main .app-main-scroll  flex-1 / min-h-0 / overflow-y-auto ← 唯一滚动层
 *  │                 └─ Outlet
 *  └─ footer .app-footer（可选，随内容区展开）
 */
export default function Layout() {
  const { pathname } = useLocation()
  const { user, logout } = useAuth()
  const { isVue } = useStyleMode()
  const navigate = useNavigate()

  const initial = useMemo(() => readLayout(), [])
  const [sidebarMode, setSidebarMode] = useState(initial.sidebarMode)
  const [headerVisible, setHeaderVisible] = useState(initial.headerVisible)
  const [openKeys, setOpenKeys] = useState(initial.openKeys)

  useEffect(() => {
    writeLayout({ sidebarMode, headerVisible, openKeys })
  }, [sidebarMode, headerVisible, openKeys])

  const toggleSidebar = () => setSidebarMode((prev) => {
    if (prev === 'hidden') return 'expanded'
    if (prev === 'expanded') return 'collapsed'
    return 'hidden'
  })
  const cycleHeader = () => setHeaderVisible((v) => !v)

  const onMenuClick = ({ key }) => navigate(key)

  /* —— 用户下拉菜单 —— */
  const userMenuItems = [
    { key: 'logout', icon: <LogoutOutlined />, label: '退出登录', danger: true },
  ]
  const onUserMenu = ({ key }) => {
    if (key === 'logout') { logout(); navigate('/login', { replace: true }) }
  }

  /* —— 选中状态：精确匹配 / 前缀匹配 —— */
  const selectedKeys = useMemo(() => {
    // 优先精确匹配
    const exact = navItems.flatMap(i => i.children ? i.children.map(c => c.key) : [i.key])
      .filter(k => k === pathname)
    if (exact.length) return exact
    // 前缀匹配（取最长匹配）
    const prefix = navItems.flatMap(i => i.children ? i.children.map(c => c.key) : [i.key])
      .filter(k => k !== '/' && pathname.startsWith(k))
      .sort((a, b) => b.length - a.length)
    return prefix.length ? [prefix[0]] : []
  }, [pathname])

  const isCollapsed = sidebarMode === 'collapsed'

  /* —— 监听 Vue SFC 页面发起的跳转请求 —— */
  useEffect(() => {
    const onNav = (e) => {
      const p = e.detail?.path
      if (p && typeof p === 'string') navigate(p)
    }
    window.addEventListener('app:navigate', onNav)
    return () => window.removeEventListener('app:navigate', onNav)
  }, [navigate])

  return (
    <div className={`app-shell ${headerVisible ? 'header-on' : 'header-off'} sidebar-${sidebarMode}`}>
      {/* ========== 顶部导航（可隐藏） ========== */}
      <header className="app-header" aria-hidden={!headerVisible}>
        <div className="header-left">
          <Tooltip title={`侧边栏：${sidebarMode === 'expanded' ? '点击折叠' : sidebarMode === 'collapsed' ? '点击隐藏' : '点击展开'}`}>
            <Button
              type="text"
              className="sidebar-toggle-btn"
              icon={sidebarMode === 'expanded' ? <MenuFoldOutlined /> : <MenuUnfoldOutlined />}
              onClick={toggleSidebar}
            />
          </Tooltip>

          <div className="brand" onClick={() => setSidebarMode(p => p === 'hidden' ? 'expanded' : p)}>
            <ThunderboltOutlined className="brand-logo" />
            <Text strong className="brand-name">星际控制台</Text>
          </div>
        </div>

        <div className="header-right">
          <Tooltip title={headerVisible ? '隐藏顶部导航栏' : '显示顶部导航栏'}>
            <Button
              type="text"
              className="header-toggle-btn"
              icon={headerVisible ? <EyeInvisibleOutlined /> : <EyeOutlined />}
              onClick={cycleHeader}
            />
          </Tooltip>

          {user && (
            <Dropdown menu={{ items: userMenuItems, onClick: onUserMenu }} placement="bottomRight">
              <div className="user-chip-antd">
                <Avatar size="small" style={{ background: '#1677ff' }}>
                  {user.name?.charAt(0).toUpperCase() || 'U'}
                </Avatar>
                <Text className="user-name-text">{user.name}</Text>
                <DownOutlined style={{ fontSize: '0.7rem', color: 'var(--c-text-3, #00000073)' }} />
              </div>
            </Dropdown>
          )}
        </div>
      </header>

      {/* ========== 中部：左侧栏 + 右侧内容（唯一滚动容器在这里） ========== */}
      <section className="app-body">
        <aside className="app-sidebar" aria-label="侧边导航">
          <div className="sidebar-scroll">
            {isVue ? (
              <VueMenu
                items={navItems}
                collapsed={isCollapsed}
                openKeys={isCollapsed ? [] : openKeys}
                onOpenChange={setOpenKeys}
              />
            ) : (
              <Menu
                mode="inline"
                theme="light"
                items={navItems}
                selectedKeys={selectedKeys}
                openKeys={isCollapsed ? [] : openKeys}
                onOpenChange={setOpenKeys}
                onClick={onMenuClick}
                inlineCollapsed={isCollapsed}
                className="sidebar-menu"
              />
            )}
          </div>

          {sidebarMode === 'expanded' && (
            <div className="sidebar-foot">
              <Badge status="processing" />
              <Text type="secondary" style={{ fontSize: '0.75rem' }}>
                点击左上角按钮切换：折叠 / 隐藏
              </Text>
            </div>
          )}
        </aside>

        <div className="app-main-wrap">
          <main className="app-main-scroll" role="main">
            <Outlet />
            <footer className="app-footer">
              <Text type="secondary" style={{ fontSize: '0.8rem' }}>
                © {new Date().getFullYear()} 星际控制台 · Built with Ant Design
              </Text>
            </footer>
          </main>
        </div>
      </section>

      {/* ========== 应急浮动入口（仅在 header 隐藏时出现） ========== */}
      <div
        className={`emergency-fab ${headerVisible ? '' : 'show-header-btn'}`}
        aria-hidden={headerVisible}
      >
        {!headerVisible && (
          <Tooltip title="显示顶部导航栏">
            <Button
              type="primary"
              shape="circle"
              icon={<EyeOutlined />}
              onClick={cycleHeader}
            />
          </Tooltip>
        )}
        {!headerVisible && sidebarMode === 'hidden' && (
          <Tooltip title="展开侧边栏">
            <Button
              shape="circle"
              icon={<MenuUnfoldOutlined />}
              onClick={toggleSidebar}
            />
          </Tooltip>
        )}
      </div>

      {/* 助手中心：AI Agent + 语音助手 + 可拖动快捷助手键 */}
      <Assistants />
    </div>
  )
}

// packages/@myorg/vue-admin-shell/src/Layout.vue
<script setup>
import { ref, computed, watch } from 'vue'
import { useRoute, useRouter, RouterLink, RouterView } from 'vue-router'
import { useAuth } from '@myorg/vue-core-composables'
import GlobalAgent from './GlobalAgent.vue'
import './Layout.scss'

/**
 * 分组导航配置：
 * - type: 'link'  顶层直达链接
 * - type: 'group' 折叠分组（在侧边栏里手风琴展开/收起）
 */
const navGroups = [
  { type: 'link', to: '/', label: '首页', icon: '🏠', end: true },
  {
    type: 'group',
    label: 'AI 助手',
    icon: '🤖',
    defaultOpen: false,
    children: [
      { to: '/voice', label: '语音助手', icon: '🎙️', desc: '语音识别与播报' },
      { to: '/agent', label: 'AI Agent 控制台', icon: '🎯', desc: '自然语言驱动页面操作' },
    ],
  },
  {
    type: 'group',
    label: '工具箱',
    icon: '🧰',
    defaultOpen: true,
    children: [
      { to: '/scan', label: '扫码', icon: '📱', desc: '摄像头扫码识别' },
      { to: '/embed', label: '嵌套预览', icon: '🖼️', desc: 'iframe 嵌套演示' },
      { to: '/form-builder', label: '配置表单', icon: '📝', desc: 'JSON 驱动动态表单' },
      { to: '/theme', label: '主题切换', icon: '🎨', desc: '暗/亮/跟随系统三态主题' },
      { to: '/charts', label: 'SVG 图表', icon: '📈', desc: '纯 SVG 图表组件演示' },
      { to: '/command-palette', label: '命令面板', icon: '⌘', desc: 'Cmd/K 全局搜索导航' },
      { to: '/notify', label: '通知中心', icon: '🔔', desc: 'Toast 与通知抽屉' },
      { to: '/data-table', label: '高级表格', icon: '📋', desc: '排序筛选分页行选择' },
      { to: '/login', label: '星空登录', icon: '🔐', desc: '星际登录页' },
    ],
  },
  { type: 'link', to: '/dashboard', label: '控制台', icon: '📊' },
  { type: 'link', to: '/test-center', label: '测试中心', icon: '🧪' },
  { type: 'link', to: '/about', label: '关于', icon: 'ℹ️' },
]

const LS_KEY = 'app.layout.v1'
const DEFAULT = { sidebarMode: 'expanded', headerVisible: true, collapsed: {} }

function readLayout() {
  try {
    const raw = localStorage.getItem(LS_KEY)
    if (!raw) return DEFAULT
    const parsed = JSON.parse(raw)
    return { ...DEFAULT, ...parsed, collapsed: { ...DEFAULT.collapsed, ...(parsed.collapsed || {}) } }
  } catch {
    return DEFAULT
  }
}
function writeLayout(v) {
  try { localStorage.setItem(LS_KEY, JSON.stringify(v)) } catch { /* ignore */ }
}

const route = useRoute()
const router = useRouter()
const { user, logout } = useAuth()

const initial = readLayout()
const sidebarMode = ref(initial.sidebarMode)        // 'expanded' | 'collapsed' | 'hidden'
const headerVisible = ref(initial.headerVisible)     // boolean
const collapsed = ref(initial.collapsed)             // group 手风琴：{ [groupLabel]: boolean }

// 持久化用户偏好
watch([sidebarMode, headerVisible, collapsed], () => {
  writeLayout({ sidebarMode: sidebarMode.value, headerVisible: headerVisible.value, collapsed: collapsed.value })
}, { deep: true })

const shellClass = computed(() => [
  'app-shell',
  headerVisible.value ? 'header-on' : 'header-off',
  `sidebar-${sidebarMode.value}`,
])

const linkActive = (to, end) => {
  const p = route.path
  if (end) return p === to
  return p === to || p.startsWith(to + '/')
}

const isGroupActive = (group) =>
  group.children.some((child) => linkActive(child.to, child.to === '/'))

const toggleSidebar = () => {
  const prev = sidebarMode.value
  sidebarMode.value = prev === 'hidden' ? 'expanded' : prev === 'expanded' ? 'collapsed' : 'hidden'
}
const cycleHeader = () => { headerVisible.value = !headerVisible.value }
const openSidebarIfHidden = () => { if (sidebarMode.value === 'hidden') sidebarMode.value = 'expanded' }

const toggleGroup = (label, defaultOpen = false) => {
  const current = collapsed.value[label] ?? !defaultOpen
  collapsed.value = { ...collapsed.value, [label]: !current }
}

const onLogout = () => {
  logout()
  router.push('/login')
}
</script>

<template>
  <div :class="shellClass">
    <!-- ========== 顶部导航（可隐藏） ========== -->
    <header class="app-header" :aria-hidden="!headerVisible">
      <div class="header-left">
        <button
          type="button"
          class="icon-btn sidebar-toggle"
          @click="toggleSidebar"
          :title="sidebarMode === 'expanded' ? '点击折叠' : sidebarMode === 'collapsed' ? '点击隐藏' : '点击展开'"
          aria-label="切换侧边栏（展开 / 折叠 / 隐藏）"
        >
          <!-- 侧边栏三态图标 -->
          <svg v-if="sidebarMode === 'hidden'" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M4 6h16" /><path d="M4 12h10" /><path d="M4 18h16" /><path d="M17 9l4 3-4 3" stroke-width="2" />
          </svg>
          <svg v-else-if="sidebarMode === 'collapsed'" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <rect x="3" y="4" width="5" height="16" rx="1.5" /><rect x="10" y="4" width="11" height="16" rx="1.5" /><path d="M14 15l3-3-3-3" />
          </svg>
          <svg v-else viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <rect x="3" y="4" width="11" height="16" rx="1.5" /><rect x="16" y="4" width="5" height="16" rx="1.5" /><path d="M6 9l-3 3 3 3" />
          </svg>
        </button>

        <div class="brand" @click="openSidebarIfHidden" title="点击展开侧边栏">
          <span class="brand-logo" aria-hidden="true">⚡</span>
          <span class="brand-name">星际控制台</span>
        </div>
      </div>

      <div class="header-right">
        <button
          type="button"
          class="icon-btn header-toggle"
          @click="cycleHeader"
          :title="headerVisible ? '隐藏顶部导航栏' : '显示顶部导航栏'"
          aria-label="切换顶部导航栏显示"
        >
          <svg v-if="headerVisible" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M3 3l18 18" /><path d="M10.6 5.1A10.7 10.7 0 0 1 12 5c7 0 10 7 10 7a13.2 13.2 0 0 1-2.2 3.1M6.1 6.1C3.3 7.9 2 12 2 12s3 7 10 7a9.7 9.7 0 0 0 4.3-1" /><path d="M9.9 9.9a3 3 0 1 0 4.2 4.2" />
          </svg>
          <svg v-else viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12Z" /><circle cx="12" cy="12" r="3" />
          </svg>
        </button>

        <div v-if="user" class="user-chip">
          <span class="user-chip-avatar" aria-hidden="true">{{ (user.name?.charAt(0) || 'U').toUpperCase() }}</span>
          <span class="user-chip-name">{{ user.name }}</span>
          <button type="button" class="user-chip-logout" @click="onLogout" title="登出" aria-label="登出">⏻</button>
        </div>
      </div>
    </header>

    <!-- ========== 中部：左侧栏 + 右侧内容（唯一滚动容器在这里） ========== -->
    <section class="app-body">
      <aside class="app-sidebar" aria-label="侧边导航">
        <nav class="sidebar-nav">
          <ul>
            <template v-for="item in navGroups" :key="item.type === 'link' ? item.to : item.label">
              <!-- group -->
              <li v-if="item.type === 'group'" :class="['sidebar-li', 'sidebar-group', isGroupActive(item) ? 'group-active' : '']">
                <!-- 折叠态：带 tooltip 的按钮 + 悬浮展开菜单 -->
                <template v-if="sidebarMode === 'collapsed'">
                  <button type="button" class="sidebar-link sidebar-trigger" :title="item.label">
                    <span class="sidebar-icon">{{ item.icon }}</span>
                    <span class="sidebar-label">{{ item.label }}</span>
                  </button>
                  <ul class="sidebar-popover" role="menu">
                    <li class="popover-title">{{ item.label }}</li>
                    <li v-for="child in item.children" :key="child.to">
                      <RouterLink :to="child.to" custom v-slot="{ href, navigate, isActive }">
                        <a
                          :href="href"
                          :class="['popover-item', isActive ? 'active' : '']"
                          @click="navigate"
                        >
                          <span class="popover-icon">{{ child.icon }}</span>
                          <span class="popover-texts">
                            <span class="popover-label">{{ child.label }}</span>
                            <span v-if="child.desc" class="popover-desc">{{ child.desc }}</span>
                          </span>
                        </a>
                      </RouterLink>
                    </li>
                  </ul>
                </template>

                <template v-else>
                  <button
                    type="button"
                    :class="['sidebar-link', 'sidebar-trigger', collapsed[item.label] ?? !item.defaultOpen ? 'is-collapsed' : 'is-open']"
                    @click="toggleGroup(item.label, item.defaultOpen)"
                    :aria-expanded="!(collapsed[item.label] ?? !item.defaultOpen)"
                  >
                    <span class="sidebar-icon">{{ item.icon }}</span>
                    <span class="sidebar-label">{{ item.label }}</span>
                    <span class="sidebar-caret" aria-hidden="true">▾</span>
                  </button>

                  <ul :class="['sidebar-children', collapsed[item.label] ?? !item.defaultOpen ? 'is-collapsed' : 'is-open']">
                    <div class="sidebar-children-inner">
                      <li v-for="child in item.children" :key="child.to">
                        <RouterLink :to="child.to" custom v-slot="{ href, navigate, isActive }">
                          <a :href="href" :class="['sidebar-children-link', isActive ? 'active' : '']" @click="navigate">
                            <span class="sidebar-children-icon">{{ child.icon }}</span>
                            <span class="sidebar-children-texts">
                              <span class="sidebar-children-label">{{ child.label }}</span>
                              <span v-if="child.desc" class="sidebar-children-desc">{{ child.desc }}</span>
                            </span>
                          </a>
                        </RouterLink>
                      </li>
                    </div>
                  </ul>
                </template>
              </li>

              <!-- link -->
              <li v-else class="sidebar-li">
                <RouterLink :to="item.to" custom v-slot="{ href, navigate, isActive }">
                  <a
                    :href="href"
                    :class="['sidebar-link', linkActive(item.to, item.end) || isActive ? 'active' : '']"
                    :title="sidebarMode === 'collapsed' ? item.label : undefined"
                    @click="navigate"
                  >
                    <span class="sidebar-icon">{{ item.icon }}</span>
                    <span class="sidebar-label">{{ item.label }}</span>
                  </a>
                </RouterLink>
              </li>
            </template>
          </ul>
        </nav>

        <div v-if="sidebarMode === 'expanded'" class="sidebar-foot" aria-hidden="true">
          <span class="sidebar-foot-dot" />
          点击左上角按钮切换：折叠 / 隐藏
        </div>
      </aside>

      <div class="app-main-wrap">
        <main class="app-main-scroll" role="main">
          <RouterView />
          <footer class="app-footer">
            <p>© {{ new Date().getFullYear() }} 星际控制台 · Built with ❤️</p>
          </footer>
        </main>
      </div>
    </section>

    <!-- ========== 应急浮动入口（header 隐藏 或 sidebar 隐藏 时仍然可见） ========== -->
    <div
      :class="['emergency-fab', !headerVisible ? 'show-header-btn' : '', sidebarMode === 'hidden' ? 'show-sidebar-btn' : '']"
      :aria-hidden="headerVisible && sidebarMode !== 'hidden'"
    >
      <button
        v-if="!headerVisible"
        type="button"
        class="fab-btn fab-show-header"
        @click="cycleHeader"
        title="显示顶部导航栏"
        aria-label="显示顶部导航栏"
      >
        <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12Z" /><circle cx="12" cy="12" r="3" />
        </svg>
      </button>
      <button
        v-if="sidebarMode === 'hidden'"
        type="button"
        class="fab-btn fab-show-sidebar"
        @click="toggleSidebar"
        title="展开侧边栏"
        aria-label="展开侧边栏"
      >
        <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M4 6h16" /><path d="M4 12h10" /><path d="M4 18h16" /><path d="M17 9l4 3-4 3" stroke-width="2" />
        </svg>
      </button>
    </div>

    <GlobalAgent />
  </div>
</template>
